function solution(participant, completion) {
    const map = new Map();

    for(let i = 0; i < participant.length; i++) {
        let a = participant[i], 
            b = completion[i];

        map.set(a, (map.get(a) || 0) + 1);
        map.set(b, (map.get(b) || 0) - 1);
    }

    console.log(map)

    for(let [k, v] of map) {
        console.log(k,v)
        // if(v > 0) return k;
    }

    return 'nothing';
}

console.log(solution(["leo", "kiki", "eden"],	["eden", "kiki"]))